# -*- coding: utf-8 -*-
"""TriBeamNet_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_xlWz0VMzdodY5QRp0C7tIMcUur0ZKW
"""

!pip install torch torchvision torchaudio --quiet
!pip install monai --quiet
!pip install scipy --quiet
!pip install tensorboard --quiet
!pip install gdown

import gdown
import zipfile
import os

# Step 1: Download from Google Drive
file_id = '1skgY3v8mCYSshoDFxBDtBUpVovSjMCIH'  # Change this as needed
output_zip = '/content/bf_data.zip'

print("[INFO] Downloading zip file...")
gdown.download(f'https://drive.google.com/uc?id={file_id}', output_zip, quiet=False)

# Step 2: Unzip
extract_dir = '/content'
print("[INFO] Extracting zip file...")
with zipfile.ZipFile(output_zip, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)
print("[INFO] Extraction complete.")

# Step 3: Recursively list all .h5 files
h5_files = []
for root, _, files in os.walk(extract_dir):
    for f in files:
        if f.endswith('.h5'):
            h5_files.append(os.path.join(root, f))

# Step 4: Display results
if h5_files:
    print(f"[INFO] Found {len(h5_files)} .h5 files.")
    for f in sorted(h5_files[:5]):
        print(f"  - {f}")
    # Example usage of one file
    filePath = h5_files[0]
    print(f"[INFO] First .h5 file path: {filePath}")
else:
    print("[ERROR] No .h5 files found in the extracted zip.")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split
from torch.utils.tensorboard import SummaryWriter
from torch.cuda.amp import autocast, GradScaler
from torch.optim.lr_scheduler import ReduceLROnPlateau

import numpy as np
import h5py
import random
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from monai.networks.layers import HilbertTransform
import warnings
import logging
from typing import Dict, List, Tuple, Optional
from pathlib import Path
from scipy.signal import decimate # Added import for downsampling
warnings.filterwarnings('ignore')

class AntiRectifier(nn.Module):
    """Improved AntiRectifier with better normalization"""
    def __init__(self, eps: float = 1e-8):
        super().__init__()
        self.eps = eps

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Center the data
        x = x - torch.mean(x, dim=1, keepdim=True)

        # Normalize with epsilon for stability
        x = F.normalize(x, p=2, dim=1, eps=self.eps)

        # Concatenate positive and negative parts
        return torch.cat([F.relu(x), F.relu(-x)], dim=1)

class DoubleConv(nn.Module):
    def __init__(self, in_channels: int, out_channels: int,
                 mid_channels: Optional[int] = None):
        super().__init__()
        mid_channels = mid_channels or out_channels

        self.conv1 = nn.Conv2d(in_channels, mid_channels, kernel_size=3, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(mid_channels)
        self.act1 = AntiRectifier()

        self.conv2 = nn.Conv2d(2 * mid_channels, out_channels, kernel_size=3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.act2 = nn.ReLU(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.act1(x)

        x = self.conv2(x)
        x = self.bn2(x)
        x = self.act2(x)

        return x

class Down(nn.Module):
    """Downsampling block"""
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        self.block = nn.Sequential(
            nn.MaxPool2d(2),
            DoubleConv(in_channels, out_channels)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)

class Up(nn.Module):
    """Upsampling block with improved concatenation"""
    def __init__(self, in_channels: int, out_channels: int,
                 bilinear: bool = True):
        super().__init__()
        if bilinear:
            self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
            self.conv = DoubleConv(in_channels, out_channels, in_channels // 2)
        else:
            self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)
            self.conv = DoubleConv(in_channels, out_channels)

    def forward(self, x1: torch.Tensor, x2: torch.Tensor) -> torch.Tensor:
        x1 = self.up(x1)
        # Ensure spatial dimensions match
        x1 = F.interpolate(x1, size=x2.shape[2:], mode='bilinear', align_corners=False)
        x = torch.cat([x2, x1], dim=1)
        return self.conv(x)

class BeamformingHead(nn.Module):
    """Improved beamforming head with better weight initialization"""
    def __init__(self, in_channels: int, n_elements: int):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, n_elements * 2, kernel_size=3, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(n_elements * 2)
        self.conv2 = nn.Conv2d(n_elements * 2, n_elements, kernel_size=1)

        # Initialize weights properly
        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.bn1(self.conv1(x)))
        weights = self.conv2(x)
        return F.softmax(weights, dim=1)

class FixedUNetBeamformer(nn.Module):
    """Improved UNet beamformer with better architecture"""
    def __init__(self, n_elements: int = 128, n_tasks: int = 3):
        super().__init__()
        self.n_elements = n_elements

        # Encoder
        self.inc = DoubleConv(n_elements, 64)
        self.down1 = Down(64, 128)
        self.down2 = Down(128, 256)
        self.down3 = Down(256, 512)

        # Decoder
        self.up1 = Up(768, 256, bilinear=True)
        self.up2 = Up(384, 128, bilinear=True)
        self.up3 = Up(192, 64, bilinear=True)

        # Task-specific heads
        self.das_head = BeamformingHead(64, n_elements)
        self.fdmas_head = BeamformingHead(64, n_elements)
        self.capon_head = BeamformingHead(64, n_elements)

        # Initialize weights
        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x: torch.Tensor) -> Dict[str, torch.Tensor]:
        # Store original input for beamforming
        original_input = x

        # Add input validation
        if torch.isnan(x).any() or torch.isinf(x).any():
            print("NaN or Inf detected in input")
            x = torch.nan_to_num(x, nan=0.0, posinf=1.0, neginf=-1.0)

        # Encoder
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)

        # Decoder
        x = self.up1(x4, x3)
        x = self.up2(x, x2)
        features = self.up3(x, x1)

        # Generate weights
        das_weights = self.das_head(features)
        fdmas_weights = self.fdmas_head(features)
        capon_weights = self.capon_head(features)

        # Beamforming with input validation
        original_input = torch.nan_to_num(original_input, nan=0.0, posinf=1.0, neginf=-1.0)

        das_output = torch.sum(das_weights * original_input, dim=1, keepdim=True)
        fdmas_output = torch.sum(fdmas_weights * original_input, dim=1, keepdim=True)
        capon_output = torch.sum(capon_weights * original_input, dim=1, keepdim=True)

        return {
            'das': das_output,
            'fdmas': fdmas_output,
            'capon': capon_output
        }

class FixedCustomDatasetTriBeamNet(Dataset):
    """Improved dataset class for TriBeamNet with configurable sampling and probe settings"""
    def __init__(self, folder_path: str, patch_rows: int = 128,
                 seed: int = 42, max_files: int = 1000,
                 fs: int = 31250000, probe_geometry: np.ndarray = None):
        super().__init__()
        self.folder_path = Path(folder_path)
        self.file_paths = sorted([f for f in self.folder_path.glob("*.h5")])[:max_files]
        self.rows = patch_rows
        self.fs = fs
        self.probe_geometry = probe_geometry if probe_geometry is not None else np.linspace(-0.019105, 0.019105, 128)
        random.seed(seed)

        if not self.file_paths:
            raise ValueError(f"No HDF5 files found in {folder_path}")

        print(f"Dataset initialized with {len(self.file_paths)} files")

        self.global_mean = 0.0
        self.global_std = 1.0
        self.compute_global_stats()

    def compute_global_stats(self):
        """Compute global statistics for normalization"""
        print("Computing global statistics...")
        all_values = []
        sample_size = min(10, len(self.file_paths))

        for path in self.file_paths[:sample_size]:
            try:
                with h5py.File(path, 'r') as f:
                    raw_rf = f['raw_data'][:][0].T
                    tofc = self.tofc_mapping(raw_rf)
                    tofc = np.nan_to_num(tofc, nan=0.0, posinf=1.0, neginf=-1.0)
                    all_values.append(tofc.flatten())
            except Exception as e:
                print(f"Error processing {path}: {e}")

        if all_values:
            all_values = np.concatenate(all_values)
            self.global_mean = np.median(all_values)
            self.global_std = np.std(all_values)
            if self.global_std == 0:
                self.global_std = 1.0
            print(f"Global stats - Mean: {self.global_mean:.4f}, Std: {self.global_std:.4f}")
        else:
            print("No valid data found for stats computation. Using default values.")

    def __len__(self) -> int:
        return len(self.file_paths)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        path = self.file_paths[idx]
        try:
            with h5py.File(path, 'r') as f:
                raw_rf = f['raw_data'][:][0].T

                gt_bf_datas = []
                for key in ['DAS', 'FDMAS', 'Capon']:
                    try:
                        bf_data = f[f'bf_data_{key}_real'][:].astype(np.float32)
                        scale = f.attrs[f'scale_{key}_real']
                        bf_data *= scale
                        bf_data = np.nan_to_num(bf_data, nan=0.0, posinf=1.0, neginf=-1.0)
                        if bf_data.shape[1] == 4352:
                            bf_data = decimate(bf_data, q=2, axis=1)
                        gt_bf_datas.append(bf_data)
                    except Exception as e:
                        print(f"Missing {key} in {path.name}, filling with zeros. Error: {e}")
                        gt_bf_datas.append(np.zeros((128, 2176), dtype=np.float32))

                tofc = self.tofc_mapping(raw_rf)
                tofc = np.nan_to_num(tofc, nan=0.0, posinf=1.0, neginf=-1.0)

                valid_rows = tofc.shape[0]
                max_start = max(0, valid_rows - self.rows)
                start = np.random.randint(0, max_start + 1) if max_start > 0 else 0
                end = start + self.rows

                input_patch = tofc[start:end, :, :]
                gt_patches = [gt[:, start:end].T for gt in gt_bf_datas]

                if input_patch.shape[0] != self.rows:
                    pad = self.rows - input_patch.shape[0]
                    input_patch = np.pad(input_patch, ((0, pad), (0, 0), (0, 0)), mode='constant')
                    gt_patches = [np.pad(p, ((0, pad), (0, 0)), mode='constant') for p in gt_patches]

                input_patch = self.normalize_input(input_patch)
                gt_patches = [self.normalize_target(p) for p in gt_patches]

                input_tensor = torch.from_numpy(input_patch.transpose(2, 0, 1)).float()
                output_tensor = torch.from_numpy(np.stack(gt_patches, axis=0)).float()

                return {'input': input_tensor, 'output': output_tensor}

        except Exception as e:
            print(f"Error loading file {path}: {e}")
            return {'input': torch.randn(128, self.rows, 128), 'output': torch.randn(3, self.rows, 128)}

    def normalize_input(self, data: np.ndarray) -> np.ndarray:
        return (data - self.global_mean) / (self.global_std + 1e-8)

    def normalize_target(self, data: np.ndarray) -> np.ndarray:
        mean, std = np.mean(data), np.std(data)
        if std == 0: std = 1.0
        return (data - mean) / (std + 1e-8)

    def tofc_mapping(self, rf_data: np.ndarray) -> np.ndarray:
        try:
            c = 1540
            time = np.arange(rf_data.shape[0]) / self.fs
            x = np.linspace(self.probe_geometry[0], self.probe_geometry[-1], rf_data.shape[1])
            z = 0.5 * c * time
            xg, zg = np.meshgrid(x, z)
            x_flat, z_flat = xg.ravel(), zg.ravel()

            delay_map = np.zeros((rf_data.shape[0] * rf_data.shape[1], rf_data.shape[1]))
            for i in range(rf_data.shape[1]):
                rx_delay = np.sqrt((self.probe_geometry[i] - x_flat) ** 2 + z_flat ** 2)
                total_delay = (z_flat + rx_delay) / c
                interp = interp1d(time, rf_data[:, i], kind='cubic', fill_value=0, bounds_error=False)
                delay_map[:, i] = interp(total_delay)

            return delay_map.reshape(rf_data.shape[0], rf_data.shape[1], rf_data.shape[1])
        except Exception as e:
            print(f"TOFC mapping failed: {e}")
            return np.zeros((rf_data.shape[0], rf_data.shape[1], rf_data.shape[1]))

from monai.networks.layers import HilbertTransform

#For 1 sample file
dataset_path = "/content/content/beamformed_dataset"
dataset = FixedCustomDatasetTriBeamNet(folder_path=dataset_path, patch_rows=128, seed=42, max_files=1000)

sample = dataset[0]
input_patch = sample['input']      # shape: [128, rows, 128]
gt_patch = sample['output']        # shape: [3, rows, 128]
print(f"Shape of gt_patch after processing: {gt_patch.shape}") # Verify the shape here

# hilbert = HilbertTransform(axis=1)
# titles = ['DAS', 'FDMAS', 'Capon']

# dynamic_range = 60.0  # dB

# plt.figure(figsize=(15, 5))
# for i in range(3):
#     bf_img = gt_patch[i].numpy()  # [rows, 128]
#     bf_tensor = torch.tensor(bf_img)

#     # Apply Hilbert envelope
#     bf_env = torch.abs(hilbert(bf_tensor))

#     # Normalize
#     # bf_env = bf_env / (torch.max(bf_env) + 1e-10)

#     # Log compression
#     bf_log = 20 * torch.log10(bf_env/torch.clip(torch.max(bf_env), min = 1e-8))

#     # Norm
#     bf_img_norm = (bf_log - torch.min(bf_log))/(torch.max(bf_log) - torch.min(bf_log))

#     # Plot
#     plt.subplot(1, 3, i + 1)
#     plt.imshow(bf_img_norm.numpy(), cmap='gray', aspect='auto')
#     plt.title(titles[i])
#     plt.axis('off')

# plt.tight_layout()
# plt.show()

def plot_ground_truth_sample(gt_patch):
    """Fixed version of your initial GT visualization"""
    hilbert = HilbertTransform(axis=1)
    titles = ['DAS', 'FDMAS', 'Capon']

    plt.figure(figsize=(5, 5))
    for i in range(3):
        bf_img = torch.tensor(gt_patch[i].numpy())  # Convert to tensor

        # Apply Hilbert envelope
        bf_env = torch.abs(hilbert(bf_img))

        # Check if we have valid data
        bf_max = torch.max(bf_env)
        if bf_max > 1e-10:
            # Log compression
            bf_log = 20 * torch.log10(torch.clamp(bf_env / bf_max, min=1e-8))

            # Normalize
            bf_min, bf_max = torch.min(bf_log), torch.max(bf_log)
            if bf_max > bf_min:
                bf_img_norm = (bf_log - bf_min) / (bf_max - bf_min)
            else:
                bf_img_norm = torch.zeros_like(bf_log)
        else:
            bf_img_norm = torch.zeros_like(bf_env)

        # Plot
        plt.subplot(1, 3, i + 1)
        plt.imshow(bf_img_norm.numpy().T, cmap='gray', aspect='auto', vmin=0, vmax=1)
        plt.title(titles[i])
        plt.axis('off')

    plt.tight_layout()
    plt.show()

plot_ground_truth_sample(gt_patch)

class FixedTrainer:
    """Improved trainer with better loss functions and monitoring"""
    def __init__(self, dataset: Dataset, batch_size: int = 4, lr: float = 1e-4,
                 num_workers: int = 2, use_amp: bool = True):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"Using device: {self.device}")

        self.model = FixedUNetBeamformer().to(self.device)

        # Use a combination of losses
        self.mse_loss = nn.MSELoss()
        self.l1_loss = nn.L1Loss()

        self.optimizer = optim.AdamW(self.model.parameters(), lr=lr, weight_decay=1e-4)
        self.scheduler = ReduceLROnPlateau(self.optimizer, mode='min', patience=10, factor=0.5, verbose=True)
        self.writer = SummaryWriter(log_dir = '/content/runs/tribeamnet_logs')

        # Mixed precision training
        self.use_amp = use_amp
        self.scaler = GradScaler() if use_amp else None

        # Dataset splits
        train_size = int(len(dataset) * 0.8)
        valid_size = len(dataset) - train_size
        self.train_set, self.valid_set = random_split(
            dataset, [train_size, valid_size],
            generator=torch.Generator().manual_seed(42)
        )

        self.train_loader = DataLoader(
            self.train_set, batch_size=batch_size, shuffle=True,
            num_workers=num_workers, pin_memory=True
        )
        self.valid_loader = DataLoader(
            self.valid_set, batch_size=batch_size, shuffle=False,
            num_workers=num_workers, pin_memory=True
        )

        print(f"Dataset split - Train: {len(self.train_set)}, Valid: {len(self.valid_set)}")

    def compute_loss(self, outputs: Dict[str, torch.Tensor],
                    targets: torch.Tensor) -> torch.Tensor:
        """Compute combined loss"""
        total_loss = 0

        for i, task in enumerate(['das', 'fdmas', 'capon']):
            pred = outputs[task]
            target = targets[:, i:i+1]

            # Combine MSE and L1 loss
            mse = self.mse_loss(pred, target)
            l1 = self.l1_loss(pred, target)

            task_loss = 0.8 * mse + 0.2 * l1
            total_loss += task_loss

        return total_loss / 3  # Average over tasks

    def train_epoch(self) -> float:
        """Train one epoch"""
        self.model.train()
        total_loss = 0
        num_batches = 0

        for batch_idx, batch in enumerate(self.train_loader):
            try:
                input_data = batch['input'].to(self.device, non_blocking=True)
                gt_output = batch['output'].to(self.device, non_blocking=True)

                self.optimizer.zero_grad()

                # Forward pass with mixed precision
                if self.use_amp:
                    with autocast():
                        outputs = self.model(input_data)
                        loss = self.compute_loss(outputs, gt_output)

                    # Backward pass
                    self.scaler.scale(loss).backward()
                    self.scaler.unscale_(self.optimizer)
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)
                    self.scaler.step(self.optimizer)
                    self.scaler.update()
                else:
                    outputs = self.model(input_data)
                    loss = self.compute_loss(outputs, gt_output)

                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)
                    self.optimizer.step()

                total_loss += loss.item()
                num_batches += 1

                if batch_idx % 10 == 0:
                    print(f"Batch {batch_idx}/{len(self.train_loader)}, Loss: {loss.item():.6f}")

            except Exception as e:
                print(f"Error in batch {batch_idx}: {e}")
                continue

        return total_loss / max(num_batches, 1)

    def validate_epoch(self) -> float:
        """Validate one epoch"""
        self.model.eval()
        total_loss = 0
        num_batches = 0

        with torch.no_grad():
            for batch in self.valid_loader:
                try:
                    input_data = batch['input'].to(self.device, non_blocking=True)
                    gt_output = batch['output'].to(self.device, non_blocking=True)

                    if self.use_amp:
                        with autocast():
                            outputs = self.model(input_data)
                            loss = self.compute_loss(outputs, gt_output)
                    else:
                        outputs = self.model(input_data)
                        loss = self.compute_loss(outputs, gt_output)

                    total_loss += loss.item()
                    num_batches += 1

                except Exception as e:
                    print(f"Error in validation batch: {e}")
                    continue

        return total_loss / max(num_batches, 1)

    def train(self, epochs: int):
      """Main training loop"""
      print(f"Starting training for {epochs} epochs...")

      best_val_loss = float('inf')

      for epoch in range(epochs):
          print(f"\nEpoch {epoch+1}/{epochs}")

          # Training
          train_loss = self.train_epoch()

          # Validation
          val_loss = self.validate_epoch()

          # Learning rate scheduling
          self.scheduler.step(val_loss)

          # Save best model
          if val_loss < best_val_loss:
              best_val_loss = val_loss
              torch.save(self.model.state_dict(), '/content/best_model.pth')
              print(f"New best model saved with val_loss: {val_loss:.6f}")

          print(f"Epoch {epoch+1} - Train Loss: {train_loss:.6f}, Val Loss: {val_loss:.6f}")

          self.writer.add_scalar('Loss/train', train_loss, epoch)
          self.writer.add_scalar('Loss/val', val_loss, epoch)
          self.writer.add_scalar('LR', self.optimizer.param_groups[0]['lr'], epoch)

          # Save checkpoint
          checkpoint_path = f'/content/checkpoint_epoch_{epoch}.pth'
          torch.save({
              'epoch': epoch,
              'model_state_dict': self.model.state_dict(),
              'optimizer_state_dict': self.optimizer.state_dict(),
              'train_loss': train_loss,
              'val_loss': val_loss,
          }, checkpoint_path)
          print("Saving model checkpoint...")

          # Visualize results after every epoch
          self.visualize_results(epoch + 1)

      print("Training completed!")


    def visualize_results(self, epoch: int):
        """Visualize training results"""
        self.model.eval()

        with torch.no_grad():
            try:
                # Get a sample from validation set
                sample = next(iter(self.valid_loader))
                input_data = sample['input'][:1].to(self.device)
                gt_output = sample['output'][:1].to(self.device)

                outputs = self.model(input_data)

                # Create visualization
                fig, axes = plt.subplots(2, 3, figsize=(4, 12))
                fig.suptitle(f'Epoch {epoch} - GT vs Pred')

                hilbert = HilbertTransform(axis=1)

                for i, task in enumerate(['das', 'fdmas', 'capon']):
                    # Ground truth
                    gt_img = gt_output[0, i].cpu()
                    gt_env = torch.abs(hilbert(gt_img))
                    gt_log = 20 * torch.log10(gt_env / torch.clamp(torch.max(gt_env), min=1e-8))
                    gt_norm = (gt_log - torch.min(gt_log)) / (torch.max(gt_log) - torch.min(gt_log) + 1e-8)

                    axes[0, i].imshow(gt_norm.numpy().T, cmap='gray', aspect='auto')
                    axes[0, i].set_title(f'GT - {task.upper()}')
                    axes[0, i].axis('off')

                    # Prediction
                    pred_img = outputs[task][0, 0].cpu()
                    pred_env = torch.abs(hilbert(pred_img))
                    pred_log = 20 * torch.log10(pred_env / torch.clamp(torch.max(pred_env), min=1e-8))
                    pred_norm = (pred_log - torch.min(pred_log)) / (torch.max(pred_log) - torch.min(pred_log) + 1e-8)

                    axes[1, i].imshow(pred_norm.numpy().T, cmap='gray', aspect='auto')
                    axes[1, i].set_title(f'Pred - {task.upper()}')
                    axes[1, i].axis('off')

                plt.tight_layout()
                plt.savefig(f'/content/results_epoch_{epoch}.png', dpi=150, bbox_inches='tight')
                plt.show()

            except Exception as e:
                print(f"Error in visualization: {e}")

    def close_writer(self):
      """Close tensorboard writer"""
      if hasattr(self, 'writer'):
        self.writer.close()

def main():
    """Main function with better error handling"""
    try:
        # Dataset configuration
        dataset_path = "/content/content/beamformed_dataset"

        if not Path(dataset_path).exists():
            print(f"Dataset path {dataset_path} not found!")
            return

        # Create dataset
        print("Creating dataset...")
        dataset = FixedCustomDatasetTriBeamNet(
            folder_path=dataset_path,
            patch_rows=128,
            seed=42,
            max_files=1000
        )

        # Create trainer
        print("Creating trainer...")
        trainer = FixedTrainer(
            dataset=dataset,
            batch_size=4,
            lr=1e-4,
            num_workers=2,
            use_amp=True
        )

        # Start training
        trainer.train(epochs=20)
        trainer.close_writer()

    except Exception as e:
        print(f"Error in main: {e}")
        raise

if __name__ == "__main__":
    main()

# %load_ext tensorboard
# %tensorboard --logdir /content/runs

import shutil
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define the source and destination paths
source_path = '/content/best_model.pth'
destination_path = '/content/drive/My Drive/best_model.pth' # Or any specific folder: '/content/drive/My Drive/my_models/best_model.pth'

# Copy the file
shutil.copy(source_path, destination_path)

print(f"Model saved to: {destination_path}")

# ---- Parameters ----
# Ensure your .pth file path is correct after mounting Google Drive
model_load_path = "/content/drive/My Drive/best_model.pth" # Corrected model path

# IMPORTANT: patch_rows MUST match the training patch size (128 from your dataset)
patch_rows = 128
# num_patches will be determined dynamically based on the actual depth of your data

# Set the path to one of the H5 files generated by your ultraspy script
# Example: "/content/beamformed_dataset/data_1.h5"
file_path = "/content/content/beamformed_dataset/data_7.h5" # Adjusted path based on your clarification
# Define fs as a constant, as it's not in the H5 file attributes
fs = 31250000

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- Mount Google Drive (essential for Colab) ---
from google.colab import drive
drive.mount('/content/drive')

# ---- Load model ----
model = FixedUNetBeamformer()
model.load_state_dict(torch.load(model_load_path, map_location=device))
model.to(device)
model.eval()
print(f"Model loaded successfully from {model_load_path} and set to {device}.")

def normalize_input(self, data: np.ndarray) -> np.ndarray:
    """Normalize input data"""
    return (data - self.global_mean) / (self.global_std + 1e-8)

def hilbert_log_compress(img, epsilon=1e-6):
    """
    Applies Hilbert transform to get envelope, then log compresses the image.
    Normalizes the image so its maximum value is 0 dB.
    Args:
        img (np.ndarray): The 2D beamformed image data.
        epsilon (float): Small value to prevent log(0).
    Returns:
        np.ndarray: The log-compressed image.
    """
    # Ensure img is 2D (depth, lateral)
    if img.ndim == 3 and img.shape[0] == 1:
        img = img.squeeze(0)

    # Apply Hilbert transform along the depth axis (axis=0)
    analytic = HilbertTransform(axis=0)(img)
    envelope = torch.abs(analytic)
    envelope_max = torch.max(envelope)

    # Handle potential issues with log(0) by clipping
    if envelope_max > 1e-10:
        # Log compression
        envelope_log = 20 * torch.log10(torch.clamp(envelope / envelope_max, min=1e-8))

        # Normalize
        envelope_min, envelope_max = torch.min(envelope_log), torch.max(envelope_log)
        if envelope_max > envelope_min:
            log_img_norm = (envelope_log - envelope_min) / (envelope_max - envelope_min)
        else:
            log_img_norm = torch.zeros_like(envelope_log)
    else:
        log_img_norm = torch.zeros_like(envelope)

    # Normalize the maximum value to 0 dB
    log_img_norm -= log_img_norm.max()
    return log_img_norm

def time_to_space_mapping(rf_data: np.ndarray, fs: int) -> np.ndarray:
    """
    Performs Time-Of-Flight Correction (TOFC) mapping.
    Args:
        rf_data (np.ndarray): Raw RF data, expected shape [time_samples, channels].
        fs (int): Sampling frequency.
    Returns:
        np.ndarray: TOFC-mapped data, shape [depth_samples, lateral_lines, channels].
    """
    c = 1540  # Speed of sound in m/s
    probe_geometry = np.linspace(-0.019105, 0.019105, 128) # Assuming 128 elements
    timeVector = np.arange(rf_data.shape[0]) / fs # Time axis for RF data

    # Lateral axis in space (assuming lateral_lines = number of channels for now)
    x_axis = np.linspace(probe_geometry[0], probe_geometry[-1], rf_data.shape[1])
    z_axis = 0.5 * c * timeVector # Depth axis in space

    x_grid, z_grid = np.meshgrid(x_axis, z_axis)
    pixels = z_grid.shape[0] * z_grid.shape[1]

    tofc_data = np.zeros((pixels, rf_data.shape[1]), dtype=np.float32)

    for nrx in range(rf_data.shape[1]): # Iterate over each receiver element (channel)
        # Calculate receive delay from each pixel to each receiver element
        receive_delay = np.sqrt((probe_geometry[nrx] - x_grid.ravel()) ** 2 + z_grid.ravel() ** 2)
        # Total two-way delay
        total_delay = (z_grid.ravel() / c) + (receive_delay / c)

        # Interpolate RF data at these total_delay times
        interp_func = interp1d(timeVector, rf_data[:, nrx], kind='cubic', fill_value=0, bounds_error=False)
        tofc_data[:, nrx] = interp_func(total_delay)

    # Reshape TOFC back to [depth_samples, lateral_lines, channels]
    result = tofc_data.reshape(z_grid.shape[0], z_grid.shape[1], rf_data.shape[1])
    return np.nan_to_num(result, nan=0.0, posinf=1.0, neginf=-1.0)

# ---- NEW NORMALIZATION FUNCTIONS ----
def compute_global_stats(tofc_data):
    """Compute global statistics for consistent normalization"""
    global_mean = np.mean(tofc_data)
    global_std = np.std(tofc_data)
    if global_std == 0:
        global_std = 1.0
    return global_mean, global_std

def normalize_input(data, global_mean, global_std):
    """Normalize input data using global statistics"""
    return (data - global_mean) / (global_std + 1e-8)

# ---- REPLACE YOUR EXISTING process_file FUNCTION WITH THIS ----
def process_file(file_path, patch_rows, fs_constant):
    with h5py.File(file_path, "r") as f:
        # Load raw data from 'raw_data'
        inp = f['raw_data'][:]

        # Load all three ground truth beamformed data and their scales
        gt_das_int16 = f['bf_data_DAS_real'][:]
        scale_das = f.attrs['scale_DAS_real']
        gt_fdmas_int16 = f['bf_data_FDMAS_real'][:]
        scale_fdmas = f.attrs['scale_FDMAS_real']
        gt_capon_int16 = f['bf_data_Capon_real'][:]
        scale_capon = f.attrs['scale_Capon_real']

        # Scale back to original float values
        gt_das_full = gt_das_int16 * scale_das
        gt_fdmas_full = gt_fdmas_int16 * scale_fdmas
        gt_capon_full = gt_capon_int16 * scale_capon

    idata = np.transpose(inp[0], (1, 0))

    # Perform Time-Of-Flight Correction (TOFC) mapping
    tofc = time_to_space_mapping(idata, fs_constant)

    # CRITICAL: Compute global statistics for consistent normalization
    global_mean, global_std = compute_global_stats(tofc)
    print(f"Global stats - Mean: {global_mean:.6f}, Std: {global_std:.6f}")

    # Determine num_patches dynamically
    total_depth = tofc.shape[0]
    num_patches = (total_depth + patch_rows - 1) // patch_rows

    # Lists to store patches
    pred_full_das = []
    pred_full_fdmas = []
    pred_full_capon = []

    # Lists to store ground truth patches
    gt_full_das_patches = []
    gt_full_fdmas_patches = []
    gt_full_capon_patches = []

    for i in range(num_patches):
        start_row = i * patch_rows
        end_row = min((i + 1) * patch_rows, total_depth)
        if start_row >= total_depth:
            break

        current_patch_rows = end_row - start_row

        input_patch_raw = tofc[start_row:end_row]

        # Extract corresponding ground truth patches
        gt_das_patch_raw = gt_das_full[start_row:end_row]
        gt_fdmas_patch_raw = gt_fdmas_full[start_row:end_row]
        gt_capon_patch_raw = gt_capon_full[start_row:end_row]

        # Pad if the last patch is smaller than patch_rows
        if current_patch_rows < patch_rows:
            padding_rows = patch_rows - current_patch_rows
            input_patch_raw = np.pad(input_patch_raw, ((0, padding_rows), (0, 0), (0, 0)),
                                   mode='constant', constant_values=0)
            gt_das_patch_raw = np.pad(gt_das_patch_raw, ((0, padding_rows), (0, 0)),
                                    mode='constant', constant_values=0)
            gt_fdmas_patch_raw = np.pad(gt_fdmas_patch_raw, ((0, padding_rows), (0, 0)),
                                      mode='constant', constant_values=0)
            gt_capon_patch_raw = np.pad(gt_capon_patch_raw, ((0, padding_rows), (0, 0)),
                                      mode='constant', constant_values=0)

        # Input patch for model: [C, H, W] -> [128, patch_rows, 128]
        input_tensor_np = np.nan_to_num(input_patch_raw.transpose(2, 0, 1))

        # FIXED: Use global normalization instead of per-patch normalization
        input_tensor_np = normalize_input(input_tensor_np, global_mean, global_std)

        # Convert to PyTorch tensor and add batch dimension
        input_tensor = torch.from_numpy(input_tensor_np).unsqueeze(0).float().to(device)

        with torch.no_grad():
            model_outputs = model(input_tensor)

        # Extract predicted patches for each beamformer
        pred_das_patch = model_outputs['das'].squeeze(0).squeeze(0).cpu().numpy()
        pred_fdmas_patch = model_outputs['fdmas'].squeeze(0).squeeze(0).cpu().numpy()
        pred_capon_patch = model_outputs['capon'].squeeze(0).squeeze(0).cpu().numpy()

        # Handle potential extra padding if last patch was smaller
        if current_patch_rows < patch_rows:
            pred_das_patch = pred_das_patch[:current_patch_rows, :]
            pred_fdmas_patch = pred_fdmas_patch[:current_patch_rows, :]
            pred_capon_patch = pred_capon_patch[:current_patch_rows, :]
            gt_das_patch_raw = gt_das_patch_raw[:current_patch_rows, :]
            gt_fdmas_patch_raw = gt_fdmas_patch_raw[:current_patch_rows, :]
            gt_capon_patch_raw = gt_capon_patch_raw[:current_patch_rows, :]

        # Append the processed (predicted and GT) patches to their respective lists
        pred_full_das.append(pred_das_patch)
        pred_full_fdmas.append(pred_fdmas_patch)
        pred_full_capon.append(pred_capon_patch)

        gt_full_das_patches.append(gt_das_patch_raw)
        gt_full_fdmas_patches.append(gt_fdmas_patch_raw)
        gt_full_capon_patches.append(gt_capon_patch_raw)

    # Stack all patches vertically to form the full images
    pred_full_das = np.vstack(pred_full_das)
    pred_full_fdmas = np.vstack(pred_full_fdmas)
    pred_full_capon = np.vstack(pred_full_capon)

    gt_full_das = np.vstack(gt_full_das_patches)
    gt_full_fdmas = np.vstack(gt_full_fdmas_patches)
    gt_full_capon = np.vstack(gt_full_capon_patches)

    return {
        'pred_das': pred_full_das,
        'pred_fdmas': pred_full_fdmas,
        'pred_capon': pred_full_capon,
        'gt_das': gt_full_das.T,
        'gt_fdmas': gt_full_fdmas.T,
        'gt_capon': gt_full_capon.T
    }


# ---- Run and Plot ----
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

results = process_file(file_path, patch_rows, fs)

def plot_all_6_ultrasound_images(results, fs=31250000, c=1540, dynamic_range_db=80):
    from scipy.signal import hilbert

    def to_dB_image(data):
        data = data / np.linalg.norm(data) if np.linalg.norm(data) > 0 else data
        envelope = np.abs(hilbert(data, axis=0))
        envelope = np.clip(envelope, 1e-8, None)
        log_compressed = 20 * np.log10(envelope)
        log_compressed = np.clip(log_compressed, -dynamic_range_db, 0)
        return log_compressed

    def get_extent(shape):
        time_vector = np.arange(shape[0]) / fs
        z_axis = 0.5 * c * time_vector * 1e3  # mm
        x_axis = np.linspace(-0.019105, 0.019105, shape[1]) * 1e3  # mm
        return [x_axis[0], x_axis[-1], z_axis[-1], z_axis[0]]

    gt_das = to_dB_image(results['gt_das'])
    gt_fdmas = to_dB_image(results['gt_fdmas'])
    gt_capon = to_dB_image(results['gt_capon'])
    pred_das = to_dB_image(results['pred_das'])
    pred_fdmas = to_dB_image(results['pred_fdmas'])
    pred_capon = to_dB_image(results['pred_capon'])

    extent = get_extent(gt_das.shape)

    fig, axes = plt.subplots(2, 3, figsize=(8, 12))
    fig.suptitle("Ultrasound GT vs Prediction (Log-compressed dB, Clipped)", fontsize=16)

    titles = [
        "GT: DAS", "GT: FDMAS", "GT: Capon",
        "Pred: DAS", "Pred: FDMAS", "Pred: Capon"
    ]
    images = [gt_das, gt_fdmas, gt_capon, pred_das, pred_fdmas, pred_capon]

    for ax, img, title in zip(axes.flat, images, titles):
        im = ax.imshow(img, cmap='gray', extent=extent, aspect='auto', vmin=-dynamic_range_db, vmax=0)
        ax.set_title(title)
        ax.set_xlabel("Lateral (mm)")
        ax.set_ylabel("Depth (mm)")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# Plot using dB-compressed pipeline
plot_all_6_ultrasound_images(results)